export const USER_GETTERS_USERS = 'USER_GETTERS_USER';
export const USER_MUTATIONS_SET_USERS = 'USER_MUTATIONS_SET_USER';
export const USER_ACTIONS_FETCH_USERS = 'USER_ACTIONS_FETCH_USERS';

export const RANK_GETTERS_LIST = 'RANK_GETTERS_LIST';
export const RANK_MUTATIONS_SET_LIST = 'RANK_MUTATIONS_SET_LIST';
export const RANK_ACTIONS_FETCH_LIST = 'RANK_ACTIONS_FETCH_LIST';

export const ZJJ_GETTERS_KEY = 'ZJJ_GETTERS_KEY';
export const ZJJ_MUTATIONS_SET_KEY = 'ZJJ_MUTATIONS_SET_KEY';
export const ZJJ_ACTIONS_FETCH_KEY = 'ZJJ_ACTIONS_FETCH_KEY';
